version: "3.7"

services:
  mtts-backend:
    restart: "no"
    build:
      context: ../../backend
      dockerfile: ../docker/development/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MARYTTS_URL: http://mtts-marytts:59125/
    volumes:
      - "../../backend:/app"
      - "mtts-pip-cache:/root/.cache/pip"

  mtts-marytts:
    restart: "no"
    image: synesthesiam/marytts:5.2
    ports:
      - "59125:59125"

  mtts-frontend:
    environment:
      - VUE_APP_MARYTTS_URL=http://localhost:59125
      - VUE_APP_API_URL=http://localhost:8000
    restart: "no"
    image: node:12
    expose:
      - 8080
    command: "./tools/run-development.sh"
    working_dir: /app
    volumes:
      - "../../frontend:/app"
      - "mtts-node_modules:/app/node_modules"

  mtts-reverse-proxy:
    image: caddy:2.4.3-alpine
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080

volumes:
  mtts-pip-cache:
  mtts-node_modules:
