version: "3.7"

services:
  mtts-backend:
    restart: "no"
    build:
      context: ../../backend
      dockerfile: ../docker/development/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MARYTTS_URL: http://mtts-marytts:59125/
    volumes:
      - "../../backend:/app"
      - "mtts-pip-cache:/root/.cache/pip"

  mtts-marytts:
    restart: "no"
    image: synesthesiam/marytts:5.2
    ports:
      - "59125:59125"

volumes:
  mtts-pip-cache:
