version: "3.7"

services:
  mtts-marytts:
    restart: "no"
    image: synesthesiam/marytts:5.2
    ports:
      - "59125:59125"

  mtts-frontend:
    environment:
      - VUE_APP_MARYTTS_URL=http://ec2-18-189-192-250.us-east-2.compute.amazonaws.com:59125
    restart: "no"
    image: node:12
    expose:
      - 8080
    command: "./tools/run-production.sh"
    working_dir: /app
    volumes:
      - "../../frontend:/app"
      - "mtts-node_modules:/app/node_modules"

  mtts-reverse-proxy:
    image: caddy:2.4.3-alpine
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8080:8080

volumes:
  mtts-node_modules:
